// Auto-generated by select_survey_samples.py
// Paste sentenceGroups into index.html

const sentenceGroups = [
  {
    "id": 5,
    "type": "mixed",
    "gt": "GT/gt_005.wav",
    "tts": "TTS/tts_005.wav",
    "waveform": "Waveform/waveform_005.wav"
  },
  {
    "id": 8,
    "type": "both_success",
    "gt": "GT/gt_008.wav",
    "tts": "TTS/tts_008.wav",
    "waveform": "Waveform/waveform_008.wav"
  },
  {
    "id": 11,
    "type": "both_success",
    "gt": "GT/gt_011.wav",
    "tts": "TTS/tts_011.wav",
    "waveform": "Waveform/waveform_011.wav"
  },
  {
    "id": 22,
    "type": "both_success",
    "gt": "GT/gt_022.wav",
    "tts": "TTS/tts_022.wav",
    "waveform": "Waveform/waveform_022.wav"
  },
  {
    "id": 25,
    "type": "mixed",
    "gt": "GT/gt_025.wav",
    "tts": "TTS/tts_025.wav",
    "waveform": "Waveform/waveform_025.wav"
  },
  {
    "id": 26,
    "type": "mixed",
    "gt": "GT/gt_026.wav",
    "tts": "TTS/tts_026.wav",
    "waveform": "Waveform/waveform_026.wav"
  },
  {
    "id": 28,
    "type": "mixed",
    "gt": "GT/gt_028.wav",
    "tts": "TTS/tts_028.wav",
    "waveform": "Waveform/waveform_028.wav"
  },
  {
    "id": 30,
    "type": "both_success",
    "gt": "GT/gt_030.wav",
    "tts": "TTS/tts_030.wav",
    "waveform": "Waveform/waveform_030.wav"
  },
  {
    "id": 43,
    "type": "both_success",
    "gt": "GT/gt_043.wav",
    "tts": "TTS/tts_043.wav",
    "waveform": "Waveform/waveform_043.wav"
  },
  {
    "id": 46,
    "type": "both_success",
    "gt": "GT/gt_046.wav",
    "tts": "TTS/tts_046.wav",
    "waveform": "Waveform/waveform_046.wav"
  },
  {
    "id": 52,
    "type": "both_success",
    "gt": "GT/gt_052.wav",
    "tts": "TTS/tts_052.wav",
    "waveform": "Waveform/waveform_052.wav"
  },
  {
    "id": 53,
    "type": "mixed",
    "gt": "GT/gt_053.wav",
    "tts": "TTS/tts_053.wav",
    "waveform": "Waveform/waveform_053.wav"
  },
  {
    "id": 58,
    "type": "mixed",
    "gt": "GT/gt_058.wav",
    "tts": "TTS/tts_058.wav",
    "waveform": "Waveform/waveform_058.wav"
  },
  {
    "id": 60,
    "type": "both_success",
    "gt": "GT/gt_060.wav",
    "tts": "TTS/tts_060.wav",
    "waveform": "Waveform/waveform_060.wav"
  },
  {
    "id": 62,
    "type": "both_success",
    "gt": "GT/gt_062.wav",
    "tts": "TTS/tts_062.wav",
    "waveform": "Waveform/waveform_062.wav"
  },
  {
    "id": 72,
    "type": "mixed",
    "gt": "GT/gt_072.wav",
    "tts": "TTS/tts_072.wav",
    "waveform": "Waveform/waveform_072.wav"
  },
  {
    "id": 77,
    "type": "both_success",
    "gt": "GT/gt_077.wav",
    "tts": "TTS/tts_077.wav",
    "waveform": "Waveform/waveform_077.wav"
  },
  {
    "id": 87,
    "type": "mixed",
    "gt": "GT/gt_087.wav",
    "tts": "TTS/tts_087.wav",
    "waveform": "Waveform/waveform_087.wav"
  },
  {
    "id": 98,
    "type": "mixed",
    "gt": "GT/gt_098.wav",
    "tts": "TTS/tts_098.wav",
    "waveform": "Waveform/waveform_098.wav"
  },
  {
    "id": 100,
    "type": "mixed",
    "gt": "GT/gt_100.wav",
    "tts": "TTS/tts_100.wav",
    "waveform": "Waveform/waveform_100.wav"
  }
];
